### ISSUE TITLE
SSML input not valid; cannot find 'speak' element.

### ISSUE THREAD

**Issue by baileyherbert** [axynos/CSGO-Text-To-Speech#1]
Latest version causing crash in audio routers including CheVolume.

Error: 0x80045009
Description: SSML input not valid; cannot find 'speak' element.

Specifically: Speak

085: IfExist, %CommandBuffer%
086: FileDelete, %CommandBuffer%
088: if LogFile = ""
089: {
090: MsgBox,Log file not specified. Please add in your logfile to the script variables section.
091: Exit
092: }
094: TTS.Speak(StartupText)

The startup text does play until the script is routed to Line 1. Any suggestions?

**Comment by axynos** [comment]
Add the log file.

**Comment by baileyherbert** [comment]
Did the trick. Thanks.
